method: bayes

metric:
  name: best_val_acc
  goal: maximize

parameters:
  start_filters:
    values: [32, 64]

  filter_organization:
    values: ['same', 'double']

  activation_pair:
    values:
      - ['ReLU', 'ReLU']
      - ['Mish', 'GELU']
      - ['SiLU', 'GELU']
      - ['GELU', 'GELU']
      - ['SiLU', 'ReLU'] 

  start_kernel:
    values: [7, 5]

  kernel_organization:
    values: ['decrease', 'same']

  learning_rate:
    distribution: log_uniform_values
    min: 1e-4
    max: 1e-3

  data_augmentation:
    values: [True]

  batch_norm:
    values: [True]

  dropout:
    distribution: uniform
    min: 0.15
    max: 0.25

  fc_neurons:
    values: [256, 512]
  
  weight_decay:
    values: [0.0, 1e-6]
