method: bayes
metric:
  name: val_acc
  goal: maximize

parameters:
  start_filters:
    values: [16, 32, 64]

  filter_organization:
    values: ['same', 'double', 'half']

  activation_pair:
    values:
      - ['ReLU', 'ReLU']
      - ['Mish', 'GELU']
      - ['SiLU', 'GELU']
      - ['GELU', 'GELU']

  kernel_size:
    values: [3, 5, 7]

  learning_rate:
    values: [0.0001, 0.001, 0.005]

  data_augmentation:
    values: [True, False]

  batch_norm:
    values: [True, False]

  dropout:
    values: [0.2, 0.3]

  fc_neurons:
    values: [128, 256, 512]